[package]
name = "ivm-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
ivm-application = { path = "../application" }
ivm-domain = { path = "../domain" }
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde_json.workspace = true
uuid.workspace = true
